# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 580fca07d67fb619dfcff70d45dfe25b5882bb48b4af7f6816519f9fd376df30536021f5dc76e0ab674c0e544e198404063700a2ccf8be6af6e780802b81fb7f

test:
  secret_key_base: ecee5e054e54236d195f4dd551ce7982dd98a835caafaee92f052c74167004a7336c7e84e1f4f5dffa9d046c611389b6795090356e105c2022766e0b3b95cb09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
